#!/bin/sh
#------------------------------------------------------------------
# Make all supported bootloaders
#------------------------------------------------------------------

make clean
make microboard_8
#make microboard_88
make microboard_168

